let _griglia_pdp_b = {
    brano_velocita: '',
    brano_correttezza: '',
    parole_velocita: '',
    parole_correttezza: '',
    notparole_velocita: '',
    notparole_correttezza: '',
    lettura_altro: '',
    brano_cronaca: '',
    brano_informativo: '',
    brano_totale: '',
    dettato_brano: '',
    omografe: '',
    lista_parole: '',
    lista_notparole: '',
    scrittura_altro: '',
    grafia_lele: '',
    grafia_uno: '',
    grafia_numeri: '',
    grafia_altro: '',
    calcolo_area_numero: '',
    calcolo_conteggio: '',
    calcolo_lettura: '',
    calcolo_scrittura: '',
    calcolo_fatti: '',
    calcolo_area_calcolo: '',
    calcolo_moltiplicazioni: '',
    calcolo_mente: '',
    calcolo_rapido: '',
    calcolo_scritte: '',
    senso_numero: '',
    senso_totale: '',
    senso_triplette: '',
    senso_inserzioni: '',
    senso_approssimativo: '',
    calcolo_aritmetici: '',
    calcolo_altro: '',
    altro_linguistica: '',
    altro_memoria: '',
    altro_attenzione: '',
    altro_elaborazione: '',
    altro_forza: ''
};

export let griglia_pdp_b = JSON.stringify(_griglia_pdp_b);