INSERT OR IGNORE INTO Materia (nome) VALUES ("Biologia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Chimica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Complementi di Matematica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Diritto ed economia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Disegno e storia dell’arte");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Disegno");
INSERT OR IGNORE INTO Materia (nome) VALUES ("DPO");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Elettronica ed Elettrotecnica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Filosofia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Fisica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Geografia Economica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Geostoria");
INSERT OR IGNORE INTO Materia (nome) VALUES ("GPO");
INSERT OR IGNORE INTO Materia (nome) VALUES ("IDP");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Informatica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Inglese");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Latino");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Lettere italiane");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Matematica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Meccanica macchine ed energia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Religione");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Scienze della Terra");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Scienze Motorie");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Scienze");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Sistemi e Automazione");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Sistemi e Reti");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Sistemi Elettronici");
INSERT OR IGNORE INTO Materia (nome) VALUES ("STA");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Storia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Tecnologia Meccanica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Telecomunicazioni");
INSERT OR IGNORE INTO Materia (nome) VALUES ("TPS");
INSERT OR IGNORE INTO Materia (nome) VALUES ("TPSI");