INSERT OR IGNORE INTO Materia (nome) VALUES ("Informatica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Scienze");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Chimica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Biologia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Matematica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Fisica");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Disegno e storia dell’arte");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Lettere italiane");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Storia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Diritto ed economia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Religione");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Inglese");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Meccanica macchine ed energia");
INSERT OR IGNORE INTO Materia (nome) VALUES ("Sistemi e automazione");